from enum import Enum
from typing import Annotated, TypeAlias

from ...core import open_enum_validator


class Type7(str, Enum):
    MAIN_C2_C = "MAIN_C2C"
    MAIN_UMFUTURE = "MAIN_UMFUTURE"
    MAIN_CMFUTURE = "MAIN_CMFUTURE"
    MAIN_MARGIN = "MAIN_MARGIN"
    MAIN_MINING = "MAIN_MINING"
    C2_C_MAIN = "C2C_MAIN"
    C2_C_UMFUTURE = "C2C_UMFUTURE"
    C2_C_MINING = "C2C_MINING"
    C2_C_MARGIN = "C2C_MARGIN"
    UMFUTURE_MAIN = "UMFUTURE_MAIN"
    UMFUTURE_C2_C = "UMFUTURE_C2C"
    UMFUTURE_MARGIN = "UMFUTURE_MARGIN"
    CMFUTURE_MAIN = "CMFUTURE_MAIN"
    CMFUTURE_MARGIN = "CMFUTURE_MARGIN"
    MARGIN_MAIN = "MARGIN_MAIN"
    MARGIN_UMFUTURE = "MARGIN_UMFUTURE"
    MARGIN_CMFUTURE = "MARGIN_CMFUTURE"
    MARGIN_MINING = "MARGIN_MINING"
    MARGIN_C2_C = "MARGIN_C2C"
    MINING_MAIN = "MINING_MAIN"
    MINING_UMFUTURE = "MINING_UMFUTURE"
    MINING_C2_C = "MINING_C2C"
    MINING_MARGIN = "MINING_MARGIN"
    MAIN_PAY = "MAIN_PAY"
    PAY_MAIN = "PAY_MAIN"
    ISOLATEDMARGIN_MARGIN = "ISOLATEDMARGIN_MARGIN"
    MARGIN_ISOLATEDMARGIN = "MARGIN_ISOLATEDMARGIN"
    ISOLATEDMARGIN_ISOLATEDMARGIN = "ISOLATEDMARGIN_ISOLATEDMARGIN"

    __str__ = str.__str__


Type7OrStr: TypeAlias = Annotated[Type7 | str, open_enum_validator(Type7)]
